name: Rust

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install trunk
      run: cargo install trunk
      
    - uses: actions/checkout@v3
    - name: Build
      run: trunk build --release
